### PR TITLE
Prevent crash in visits & track additional analytics

### LINKED ISSUE #253: Rare Crash in Visits Remote
Crash: http://crashes.to/s/634ed252a70

The date is being interpreted improperly or its nil/missing. Very strange behavior.

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #253 #279 

The app has been crashing with some bunk data coming from the back end. Instead of crashing, ignore the data and log it with the WPAnalytics package. This will allow us to determine what is wrong with the API.

Also, track the individual views of insights, days, weeks, months and years. The event should be tracked whenever the screen is shown either by tapping the segmented control or when coming from the background.

Added unit tests to ensure the tracking of the crash condition doesn't itself cause a crash.

Need Review: @daniloercoli, @sendhil

### CODE REVIEW

File: WordPressCom-Stats-iOS/WPStatsServiceRemote.m [hunk 1]
```diff
@@ -649,8 +650,15 @@ - (AFHTTPRequestOperation *)operationForVisitsForDate:(NSDate *)date
...
-            [array addObject:periodSummary];
-            dictionary[periodSummary.date] = periodSummary;
+            
+            if (periodSummary.date) {
+                [array addObject:periodSummary];
+                dictionary[periodSummary.date] = periodSummary;
+            } else {
+                DDLogError(@"operationForVisitsForDate resulted in nil date: raw date: %@", period[periodIndex]);
+                [WPAnalytics track:WPAnalyticsStatLogSpecialCondition withProperties:@{@"error_condition" : @"WPStatsServiceRemote operationForVisitsForDate:andUnit:withCompletionHandler",
+                                                                                       @"error_details" : [NSString stringWithFormat:@"Date in raw format: %@", period[periodIndex]] }];
```
Comment (jleandroperez) [inline WordPressCom-Stats-iOS/WPStatsServiceRemote.m]: What if the period is NSNotFound?. I know that shouldn't ever happen... but what if?

Comment (astralbodies) [inline WordPressCom-Stats-iOS/WPStatsServiceRemote.m]: Yeah I'm trying to "trust" the API as much as possible since we own it.

File: WordPressCom-Stats-iOS/StatsTableViewController.m [hunk 2]
```diff
@@ -1345,5 +1349,27 @@ - (void)resetDateToTodayForSite
...
+            break;
+        case StatsPeriodUnitMonth:
+            stat = WPAnalyticsStatStatsPeriodMonthsAccessed;
+            break;
+        case StatsPeriodUnitYear:
+            stat = WPAnalyticsStatStatsPeriodYearsAccessed;
+            break;
+    }
+    
+    [WPAnalytics track:stat];
```
Comment (aerych) [inline WordPressCom-Stats-iOS/StatsTableViewController.m]: Would it make sense to have a `StatsPeriodUnitUnknown`?  I ask just to cover all cases but it looks like `self.selectedPeriodUnit` should never be `nil` so maybe its not needed.

Comment (astralbodies) [inline WordPressCom-Stats-iOS/StatsTableViewController.m]: There shouldn't ever be an unknown state - and without providing a default case then there will be a compiler warning if we add another enum value.

**Comment by jleandroperez** [comment]
:shipit:

File: WordPressCom-Stats-iOS/StatsTableViewController.m (hunk 2 above)
Comment (aerych) [inline WordPressCom-Stats-iOS/StatsTableViewController.m]: :+1:
