### PR TITLE
Fixes state weirdness when switching between tabs

### LINKED ISSUE #266: Tapping around Insights vs Stats causes state issue
Reported by: @isaackeyet 

When tapping around stats, flipping between Insights and the time period stats (graph), the progress bar and progress spinner get stuck. Try to reproduce this race condition and figure out a decent way to harden the state machine between those two subviews and the pattern being used to report back progress to the parent view controller.

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #266 

How to test: 
1. Run StatsDemo using an OAuth2 token and site ID (probably swiped from WPiOS).
2. Load stats and switch between the tabs (Insights, Days, etc).
3. Do pull to refresh on the various screens and switch back and forth from Insights refreshing it too. 

@isaackeyet - I'll push a new StatsDemo with this fix in it.

Needs Review: @jleandroperez @isaackeyet

### CODE REVIEW

**Comment by astralbodies** [comment]
cc: @daniloercoli

**Comment by jleandroperez** [comment]
@astralbodies is this one ready for review?

**Comment by isaackeyet** [comment]
Just updated finally, and am still able to get it stuck.. Currently it's stuck on Insights with the spinner spinning indefinitely and the loading bar showing 100% but not going away.

**Comment by isaackeyet** [comment]
It would also seem as if when a view has already loaded and you do a pull to refresh, the top bar chart never loads (no bars show).

**Comment by isaackeyet** [comment]
Just confirmed the last one again (getting to "no bars" state). It takes a really long time for it to reload and when it does the bars are gone. iPhone 5 iOS 8.2 if that helps.

**Comment by astralbodies** [comment]
Cool, I'll give this another try with the network link conditioner set to "horrible" and see if I can reproduce it. I appreciate your diligence :grin:!!

File: WordPressCom-Stats-iOS/StatsEphemory.m [hunk 1]
```diff
@@ -76,6 +76,19 @@ - (void)removeObjectForKey:(id)key
     [self.cache removeObjectForKey:key];
 }
 
+- (void)removeAllObjectsExpectObjectForKey:(id)key
```
Comment (jleandroperez) [inline WordPressCom-Stats-iOS/StatsEphemory.m]: Please, forgive me if this is not correct. Shouldn't this method be named...

`removeAllObjectsExceptObjectWithKey` ? (Note: except instead of expect)

Comment (astralbodies) [inline WordPressCom-Stats-iOS/StatsEphemory.m]: You are certainly correct! :smile:

**Comment by astralbodies** [comment]
Got it! I'm going to merge this up into the other PRs as well so I can rebuild the StatsDemo project.
